### ISSUE TITLE
get_theme_info

### ISSUE THREAD

**Issue by vincentorback** [EarthPeople/partiwebbsidor.se#1]
Vore skoj att se vilka som gjort sidorna! Är enklare att hitta i `style.css` för dom som har WordPress men jobbig googling verkar gälla för resten.

C - OhMy!
FI - Anton Trollbäck, Maria Sjöberg, Maria Starck, Maria Söderberg, Maria Zerihoun, Therese Albertsson
FP - Stormfors
KD - ?
MP - Oktavilla
M - ?
PP - Heléne Troedsson
S - ?
SD - ?
V - Tommy Gabrielsson

**Comment by khromov** [comment]
Bra idé! :+1:

**Comment by bonny** [comment]
Håller med: bra idé! Lagt till det nu. Om någon orkar gräva fram resten av namnen så vore det topp.
